Name: Madhav Jha <br>
Roll no.: 48 <br>
Batch: E4 <br>
Branch: CSE(AIML) <br>
Semester: VI

### a. Write a Python NLTK program to find the number of male and female names in the names corpus.Print the first 10 male and female names.

#### Note: The names corpus contains a total of around 2943 male (male.txt) and 5001 female (female.txt) names.

In [ ]:
import nltk
nltk.download('all')

In [6]:
nltk.corpus.names.fileids()

['female.txt', 'male.txt']

In [7]:
maleNames = nltk.corpus.names.words('male.txt')[:10]
femaleNames = nltk.corpus.names.words('female.txt')[:10]
print("Male names: ", maleNames)
print("Female names: ", femaleNames)

Male names:  ['Aamir', 'Aaron', 'Abbey', 'Abbie', 'Abbot', 'Abbott', 'Abby', 'Abdel', 'Abdul', 'Abdulkarim']
Female names:  ['Abagael', 'Abagail', 'Abbe', 'Abbey', 'Abbi', 'Abbie', 'Abby', 'Abigael', 'Abigail', 'Abigale']

### b. Write a Python NLTK program to print the first 15 random combine labeled male and labeled female names from names corpus.

In [8]:
import random

In [9]:
print("15 random male-female combined names:")
for i in range(15):
  a = random.randint(0, len(maleNames)-1)
  b = random.randint(0, len(femaleNames)-1)
  print(maleNames[a],"-",femaleNames[b])

15 random male-female combined names:
Abbott - Abby
Abdul - Abagail
Aaron - Abbey
Abdel - Abagael
Abbey - Abagail
Abdel - Abbi
Abdulkarim - Abbi
Abdul - Abigale
Abbey - Abigael
Abbie - Abbey
Abbie - Abbey
Abdulkarim - Abigail
Abby - Abby
Abbey - Abbe
Aaron - Abagail